# Generated by Django 5.0.14 on 2026-09-15 07:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('APPLICATION_SUBMITTED', 'Application submitted'), ('APPLICATION_SHORTLISTED', 'Application shortlisted'), ('INTERVIEW_SCHEDULED', 'Interview scheduled'), ('INTERVIEW_UPDATED', 'Interview updated'), ('SELECTED', 'Selected'), ('REJECTED', 'Rejected'), ('JOB_CANCELLED', 'Job cancelled'), ('JOB_DEADLINE_REMINDER', 'Job deadline reminder'), ('NEW_APPLICATION', 'New application'), ('APPLICATION_WITHDRAWN', 'Application withdrawn'), ('INTERVIEW_RESPONSE', 'Interview response')], max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'read_at'], name='notif_recipient_read_idx'), models.Index(fields=['event', 'created_at'], name='notification_event_idx')],
            },
        ),
    ]
