# Generated by Django 5.0.14 on 2026-09-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event',
            field=models.CharField(choices=[('APPLICATION_SUBMITTED', 'Application submitted'), ('APPLICATION_SHORTLISTED', 'Application shortlisted'), ('INTERVIEW_SCHEDULED', 'Interview scheduled'), ('INTERVIEW_UPDATED', 'Interview updated'), ('SELECTED', 'Selected'), ('REJECTED', 'Rejected'), ('JOB_CANCELLED', 'Job cancelled'), ('JOB_DEADLINE_REMINDER', 'Job deadline reminder'), ('NEW_APPLICATION', 'New application'), ('APPLICATION_WITHDRAWN', 'Application withdrawn'), ('INTERVIEW_RESPONSE', 'Interview response'), ('VERIFICATION_VERIFIED', 'Business verification approved'), ('VERIFICATION_REJECTED', 'Business verification rejected'), ('VERIFICATION_REVOKED', 'Business verification revoked')], max_length=40),
        ),
    ]
