# Generated by Django 5.0.14 on 2026-09-15 08:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('profiles', '0002_studentprofile_skills'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessVerification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=20)),
                ('legal_name', models.CharField(max_length=200)),
                ('registration_reference', models.CharField(blank=True, max_length=200)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='profiles.businessprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verification_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'safety_business_verification',
            },
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('JOB', 'Job'), ('BUSINESS', 'Business'), ('USER', 'User'), ('APPLICATION', 'Application'), ('MESSAGE', 'Message')], max_length=20)),
                ('target_id', models.UUIDField()),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('CLEAR', 'Clear'), ('REVIEW', 'Review'), ('BLOCKED', 'Blocked')], default='CLEAR', max_length=20)),
                ('signals', models.JSONField(default=list)),
                ('strategy', models.CharField(default='rule_based_safety_v1', max_length=80)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'safety_risk_assessment',
            },
        ),
        migrations.CreateModel(
            name='TrustScoreSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('explanation', models.JSONField(default=dict)),
                ('strategy', models.CharField(default='rule_based_trust_v1', max_length=80)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'safety_trust_score_snapshot',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verification_history_changes', to=settings.AUTH_USER_MODEL)),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='safety.businessverification')),
            ],
            options={
                'db_table': 'safety_verification_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('JOB', 'Job'), ('BUSINESS', 'Business'), ('USER', 'User'), ('APPLICATION', 'Application'), ('MESSAGE', 'Message')], max_length=20)),
                ('target_id', models.UUIDField()),
                ('category', models.CharField(choices=[('FAKE_JOB', 'Fake job or scam'), ('HARASSMENT', 'Harassment'), ('PAYMENT_ISSUE', 'Payment issue'), ('FAKE_BUSINESS', 'Fake business'), ('INAPPROPRIATE_CONTENT', 'Inappropriate content'), ('OTHER', 'Other')], max_length=30)),
                ('description', models.TextField(max_length=5000)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('UNDER_REVIEW', 'Under review'), ('VALID', 'Valid'), ('DISMISSED', 'Dismissed'), ('ACTIONED', 'Actioned')], default='OPEN', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_filed', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'safety_report',
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='safety_report_target_idx'), models.Index(fields=['status', 'created_at'], name='safety_report_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True, max_length=3000)),
                ('status', models.CharField(choices=[('PUBLISHED', 'Published'), ('HIDDEN', 'Hidden'), ('UNDER_REVIEW', 'Under review')], default='PUBLISHED', max_length=20)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='applications.application')),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_written', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'safety_review',
                'indexes': [models.Index(fields=['reviewee', 'status'], name='safety_review_reviewee_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('application', 'reviewer'), name='uniq_review_application_reviewer'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(check=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='review_rating_1_to_5'),
        ),
        migrations.AddIndex(
            model_name='riskassessment',
            index=models.Index(fields=['status', 'score'], name='safety_risk_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='riskassessment',
            constraint=models.UniqueConstraint(fields=('target_type', 'target_id'), name='uniq_risk_target'),
        ),
        migrations.AddIndex(
            model_name='trustscoresnapshot',
            index=models.Index(fields=['subject', 'created_at'], name='safety_trust_subject_idx'),
        ),
    ]
