# Generated by Django 5.0.14 on 2026-09-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='student_profiles', through='profiles.StudentSkill', to='profiles.skill'),
        ),
    ]
