# Generated by Django 5.0.14 on 2026-09-15 14:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_role', models.CharField(blank=True, help_text="Snapshot of the actor's role at action time.", max_length=20, verbose_name='actor role')),
                ('action', models.CharField(help_text="Dotted taxonomy, e.g. 'job.publish', 'application.withdraw'.", max_length=100, verbose_name='action')),
                ('target_type', models.CharField(choices=[('USER', 'User'), ('JOB', 'Job'), ('APPLICATION', 'Application'), ('BUSINESS_VERIFICATION', 'Business verification'), ('REPORT', 'Report')], max_length=50, verbose_name='target type')),
                ('target_id', models.UUIDField(blank=True, null=True, verbose_name='target id')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Free-form context: from/to statuses, snapshot titles, request IP / user-agent, related object ids.', verbose_name='metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='User who performed the action. Null for system actions. SET_NULL so user deletion preserves the audit history; `actor_role` keeps the role readable afterwards.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'audit log',
                'verbose_name_plural': 'audit logs',
                'db_table': 'core_audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='audit_action_created_idx'), models.Index(fields=['target_type', 'target_id'], name='audit_target_idx'), models.Index(fields=['actor', 'created_at'], name='audit_actor_created_idx')],
            },
        ),
    ]
