# Generated by Django 5.0.14 on 2026-09-15 07:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0003_job_required_skills'),
        ('profiles', '0002_studentprofile_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentJobEngagement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('VIEWED', 'Viewed'), ('SAVED', 'Saved'), ('APPLIED', 'Application signal')], max_length=20)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_engagements', to='jobs.job')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_engagements', to='profiles.studentprofile')),
            ],
            options={
                'db_table': 'matching_student_job_engagement',
            },
        ),
        migrations.CreateModel(
            name='StudentPreference',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preferred_job_types', models.JSONField(blank=True, default=list)),
                ('preferred_payment_types', models.JSONField(blank=True, default=list)),
                ('minimum_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('maximum_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('maximum_distance_km', models.DecimalField(decimal_places=2, default=20, help_text='Capped by the platform 20 km discovery radius.', max_digits=6)),
                ('preferred_categories', models.ManyToManyField(blank=True, related_name='student_preferences', to='jobs.jobcategory')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='matching_preferences', to='profiles.studentprofile')),
            ],
            options={
                'db_table': 'matching_student_preference',
            },
        ),
        migrations.CreateModel(
            name='JobMatch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('skill_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('location_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('availability_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('experience_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('explanation', models.JSONField(default=dict)),
                ('strategy', models.CharField(default='rule_based_v1', max_length=80)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_matches', to='jobs.job')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_matches', to='profiles.studentprofile')),
            ],
            options={
                'db_table': 'matching_job_match',
                'ordering': ['-score', '-calculated_at'],
                'indexes': [models.Index(fields=['student', 'score'], name='match_student_score_idx'), models.Index(fields=['job', 'score'], name='match_job_score_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='jobmatch',
            constraint=models.UniqueConstraint(fields=('student', 'job'), name='uniq_matching_student_job'),
        ),
        migrations.AddIndex(
            model_name='studentjobengagement',
            index=models.Index(fields=['student', 'kind'], name='engagement_student_kind_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentjobengagement',
            constraint=models.UniqueConstraint(fields=('student', 'job', 'kind'), name='uniq_student_job_engagement'),
        ),
    ]
