# Generated by Django 5.0.14 on 2026-09-15 07:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0003_job_required_skills'),
        ('profiles', '0002_studentprofile_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cover_note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('SHORTLISTED', 'Shortlisted'), ('INTERVIEW', 'Interview'), ('SELECTED', 'Selected'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default='SUBMITTED', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='profiles.studentprofile')),
            ],
            options={
                'db_table': 'applications_application',
                'indexes': [models.Index(fields=['job', 'status'], name='application_job_status_idx'), models.Index(fields=['student', 'status'], name='application_student_status_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('job', 'student'), name='uniq_application_job_student'),
        ),
    ]
